import os
import json

from dotenv import load_dotenv
from google import genai


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise ValueError("GEMINI_API_KEY not found")

client = genai.Client(api_key=api_key)


# ============================================================
# FILE PATHS
# ============================================================

BASE_DIR = os.path.dirname(
    os.path.dirname(os.path.abspath(__file__))
)

INPUT_FILE = os.path.join(
    BASE_DIR,
    "data",
    "extracted",
    "clauses_to_review.json"
)

OUTPUT_FILE = os.path.join(
    BASE_DIR,
    "data",
    "extracted",
    "issue_detection.json"
)


# ============================================================
# LOAD CLAUSES
# ============================================================

def load_clauses():
    """
    Load clause analysis results generated by Stage 12.1.
    """

    if not os.path.exists(INPUT_FILE):

        raise FileNotFoundError(
            f"Input file not found: {INPUT_FILE}\n"
            "Run Stage 12.1 first."
        )

    with open(
        INPUT_FILE,
        "r",
        encoding="utf-8"
    ) as file:

        data = json.load(file)

    clauses = data.get("clauses", [])

    if not isinstance(clauses, list):

        raise ValueError(
            "'clauses' must be a list."
        )

    return clauses


# ============================================================
# BUILD ANALYSIS CONTEXT
# ============================================================

def build_context(clauses):
    """
    Build the context supplied to the issue detection model.
    """

    context_parts = []

    for index, clause in enumerate(
        clauses,
        start=1
    ):

        context_parts.append(
            f"""
CLAUSE {index}

Title:
{clause.get("clause_title", "Unknown")}

Category:
{clause.get("category", "Unknown")}

Current Risk:
{clause.get("risk_level", "Unknown")}

Clause Text:
{clause.get("clause_text", "")}

Why Review:
{clause.get("why_review", "")}

Potential Concern:
{clause.get("potential_concern", "")}

Recommendation:
{clause.get("recommendation", "")}

Source File:
{clause.get("source_file", "Unknown")}

Page:
{clause.get("page", "Unknown")}
"""
        )

    return "\n".join(context_parts)


# ============================================================
# DETECT ISSUES
# ============================================================

def detect_issues(clauses):
    """
    Analyze previously identified clauses and detect
    specific issues that a tenant should be aware of.
    """

    if not clauses:

        return {
            "issues": []
        }

    context = build_context(clauses)

    prompt = f"""
You are RentWise AI's Issue Detection Engine.

Your task is to analyze the previously identified rental
agreement clauses and determine the SPECIFIC issues a tenant
should be aware of.

Use ONLY the information provided below.

Do not use outside knowledge.

Do not invent facts.

------------------------------------------------------------
WHAT COUNTS AS AN ISSUE
------------------------------------------------------------

An issue may include:

1. Missing information
2. Ambiguous wording
3. Significant tenant obligation
4. Financial exposure
5. Restriction on tenant actions
6. Landlord rights that need clarification
7. Termination-related consequences
8. Potential disagreement between tenant and landlord
9. Important condition that the tenant should verify
10. Unclear responsibility or procedure

------------------------------------------------------------
IMPORTANT
------------------------------------------------------------

An "issue" does NOT automatically mean the clause is illegal,
unfair, invalid, or unenforceable.

Do not make legal conclusions.

Describe the issue factually.

------------------------------------------------------------
ISSUE TYPES
------------------------------------------------------------

Use one of these issue types:

- Missing Information
- Ambiguity
- Financial Exposure
- Tenant Obligation
- Tenant Restriction
- Landlord Right
- Termination Risk
- Payment Risk
- Responsibility Risk
- Documentation Risk
- Other

------------------------------------------------------------
SEVERITY
------------------------------------------------------------

HIGH:

Potentially significant financial, contractual, or practical
consequence for the tenant.

MEDIUM:

Meaningful issue that should be clarified or understood.

LOW:

Minor issue or relatively limited concern.

------------------------------------------------------------
REQUIRED OUTPUT
------------------------------------------------------------

Return ONLY valid JSON.

Use exactly this structure:

{{
    "issues": [
        {{
            "issue_title": "string",
            "issue_type": "string",
            "severity": "HIGH | MEDIUM | LOW",

            "description": "string",

            "potential_impact": "string",

            "what_to_verify": "string",

            "recommended_action": "string",

            "evidence": "string",

            "source_file": "string",

            "page": 1
        }}
    ]
}}

------------------------------------------------------------
ACCURACY RULES
------------------------------------------------------------

1. Every issue must be directly supported by the provided
   clause.

2. Do not invent information.

3. Do not invent amounts.

4. Do not invent deadlines.

5. Do not invent rights or obligations.

6. Do not say that something is illegal.

7. Do not say that something is legally unenforceable.

8. Do not claim that a landlord WILL take an action unless
   the clause explicitly says so.

9. Use cautious language such as:
   "may", "could", "is not specified", or
   "should be clarified" when appropriate.

10. "Evidence" must refer to the actual clause wording.

11. Source file and page must come from the input.

12. Do not create duplicate issues for the same underlying
    problem.

13. Recommendations must be practical and directly related
    to the issue.

14. Do not provide generic legal advice.

15. Preserve currency symbols and amounts exactly as supplied.

------------------------------------------------------------
CLAUSES TO ANALYZE
------------------------------------------------------------

{context}

------------------------------------------------------------
RETURN JSON ONLY
------------------------------------------------------------
"""

    response = client.models.generate_content(
        model="gemini-3.6-flash",
        contents=prompt
    )

    raw_text = response.text.strip()


    # ========================================================
    # REMOVE MARKDOWN CODE FENCES
    # ========================================================

    if raw_text.startswith("```json"):

        raw_text = raw_text[7:]

    elif raw_text.startswith("```"):

        raw_text = raw_text[3:]

    if raw_text.endswith("```"):

        raw_text = raw_text[:-3]

    raw_text = raw_text.strip()


    # ========================================================
    # PARSE JSON
    # ========================================================

    try:

        data = json.loads(raw_text)

    except json.JSONDecodeError as error:

        print("\nERROR: Gemini returned invalid JSON.")

        print("\nRaw response:")
        print(raw_text)

        print("\nJSON error:")
        print(error)

        return {
            "issues": []
        }


    # ========================================================
    # VALIDATE TOP LEVEL
    # ========================================================

    if not isinstance(data, dict):

        print(
            "\nERROR: Gemini response is not "
            "a JSON object."
        )

        return {
            "issues": []
        }


    issues = data.get(
        "issues",
        []
    )


    if not isinstance(issues, list):

        print(
            "\nERROR: 'issues' is not a list."
        )

        return {
            "issues": []
        }


    return {
        "issues": issues
    }


# ============================================================
# VALIDATE ISSUES
# ============================================================

def validate_issues(data):
    """
    Validate the structure and allowed values of
    detected issues.
    """

    issues = data.get(
        "issues",
        []
    )

    valid_issues = []


    allowed_types = [
        "Missing Information",
        "Ambiguity",
        "Financial Exposure",
        "Tenant Obligation",
        "Tenant Restriction",
        "Landlord Right",
        "Termination Risk",
        "Payment Risk",
        "Responsibility Risk",
        "Documentation Risk",
        "Other"
    ]


    allowed_severity = [
        "HIGH",
        "MEDIUM",
        "LOW"
    ]


    required_fields = [
        "issue_title",
        "issue_type",
        "severity",
        "description",
        "potential_impact",
        "what_to_verify",
        "recommended_action",
        "evidence",
        "source_file",
        "page"
    ]


    for index, issue in enumerate(
        issues,
        start=1
    ):

        if not isinstance(issue, dict):

            print(
                f"WARNING: Issue {index} "
                "is not an object."
            )

            continue


        # ----------------------------------------------------
        # CHECK REQUIRED FIELDS
        # ----------------------------------------------------

        missing_fields = [
            field
            for field in required_fields
            if field not in issue
        ]


        if missing_fields:

            print(
                f"WARNING: Issue {index} "
                f"is missing: "
                f"{', '.join(missing_fields)}"
            )

            continue


        # ----------------------------------------------------
        # NORMALIZE SEVERITY
        # ----------------------------------------------------

        severity = str(
            issue["severity"]
        ).upper().strip()


        if severity not in allowed_severity:

            print(
                f"WARNING: Invalid severity "
                f"for issue {index}: "
                f"{severity}"
            )

            continue


        issue["severity"] = severity


        # ----------------------------------------------------
        # VALIDATE ISSUE TYPE
        # ----------------------------------------------------

        issue_type = issue["issue_type"]


        if issue_type not in allowed_types:

            print(
                f"WARNING: Unknown issue type "
                f"for issue {index}: "
                f"{issue_type}"
            )

            issue["issue_type"] = "Other"


        # ----------------------------------------------------
        # VALIDATE PAGE
        # ----------------------------------------------------

        try:

            issue["page"] = int(
                issue["page"]
            )

        except (ValueError, TypeError):

            print(
                f"WARNING: Invalid page "
                f"for issue {index}: "
                f"{issue['page']}"
            )

            continue


        valid_issues.append(issue)


    return {
        "issues": valid_issues
    }


# ============================================================
# DISPLAY SUMMARY
# ============================================================

def display_summary(data):

    issues = data.get(
        "issues",
        []
    )


    high = sum(
        1
        for issue in issues
        if issue["severity"] == "HIGH"
    )


    medium = sum(
        1
        for issue in issues
        if issue["severity"] == "MEDIUM"
    )


    low = sum(
        1
        for issue in issues
        if issue["severity"] == "LOW"
    )


    print("\n" + "=" * 60)
    print("ISSUE DETECTION SUMMARY")
    print("=" * 60)

    print(
        f"\nTotal Issues: {len(issues)}"
    )

    print(
        f"[HIGH] High Severity: {high}"
    )

    print(
        f"[MEDIUM] Medium Severity: {medium}"
    )

    print(
        f"[LOW] Low Severity: {low}"
    )


# ============================================================
# DISPLAY ISSUES
# ============================================================

def display_issues(data):

    issues = data.get(
        "issues",
        []
    )


    print("\n" + "=" * 60)
    print("DETECTED ISSUES")
    print("=" * 60)


    if not issues:

        print(
            "\nNo significant issues were detected."
        )

        return


    for index, issue in enumerate(
        issues,
        start=1
    ):

        severity = issue["severity"]


        if severity == "HIGH":

            icon = "[HIGH]"

        elif severity == "MEDIUM":

            icon = "[MEDIUM]"

        else:

            icon = "[LOW]"


        print(
            f"\n{index}. {issue['issue_title']}"
        )


        print(
            f"   Type: {issue['issue_type']}"
        )


        print(
            f"   Severity: {icon} {severity}"
        )


        print(
            "\n   Description:"
        )


        print(
            f"   {issue['description']}"
        )


        print(
            "\n   Potential Impact:"
        )


        print(
            f"   {issue['potential_impact']}"
        )


        print(
            "\n   What to Verify:"
        )


        print(
            f"   {issue['what_to_verify']}"
        )


        print(
            "\n   Recommended Action:"
        )


        print(
            f"   {issue['recommended_action']}"
        )


        print(
            "\n   Evidence:"
        )


        print(
            f"   \"{issue['evidence']}\""
        )


        print(
            f"\n   Source: "
            f"{issue['source_file']}, "
            f"Page {issue['page']}"
        )


        print(
            "-" * 60
        )


# ============================================================
# SAVE RESULTS
# ============================================================

def save_results(data):

    output_directory = os.path.dirname(
        OUTPUT_FILE
    )

    os.makedirs(
        output_directory,
        exist_ok=True
    )


    with open(
        OUTPUT_FILE,
        "w",
        encoding="utf-8"
    ) as file:

        json.dump(
            data,
            file,
            indent=4,
            ensure_ascii=False
        )


    print(
        f"\nStructured issue results saved to:"
        f"\n{OUTPUT_FILE}"
    )


# ============================================================
# MAIN PROGRAM
# ============================================================

if __name__ == "__main__":

    print("\n" + "=" * 60)
    print("RENTWISE AI - STAGE 13")
    print("RISK & ISSUE DETECTION")
    print("=" * 60)


    # --------------------------------------------------------
    # STEP 1: LOAD STAGE 12.1 RESULTS
    # --------------------------------------------------------

    clauses = load_clauses()

    print(
        f"\nLoaded clauses: {len(clauses)}"
    )


    # --------------------------------------------------------
    # STEP 2: DETECT ISSUES
    # --------------------------------------------------------

    results = detect_issues(
        clauses
    )


    # --------------------------------------------------------
    # STEP 3: VALIDATE RESULTS
    # --------------------------------------------------------

    results = validate_issues(
        results
    )


    # --------------------------------------------------------
    # STEP 4: DISPLAY SUMMARY
    # --------------------------------------------------------

    display_summary(
        results
    )


    # --------------------------------------------------------
    # STEP 5: DISPLAY ISSUES
    # --------------------------------------------------------

    display_issues(
        results
    )


    # --------------------------------------------------------
    # STEP 6: SAVE JSON
    # --------------------------------------------------------

    save_results(
        results
    )


    # --------------------------------------------------------
    # COMPLETE
    # --------------------------------------------------------

    print("\n" + "=" * 60)
    print("STAGE 13 COMPLETE")
    print("=" * 60)